name: Deploy Laravel App to Ubuntu Server

on:
  push:
    branches:
      - main  # Trigger deploy only on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, curl, zip, bcmath
        coverage: none

    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction --prefer-dist

    - name: Deploy to server using SSH key authentication
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /var/www/html/app/
          git pull origin main
          composer install --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart apache2