name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, intl, xml

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up environment
        run: |
          cp .env.example .env
          php artisan key:generate
   

      - name: Set up SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite    

      - name: Run Migrations
        run: php artisan migrate --no-interaction

      - name: Run Tests
        run: php artisan test

      - name: Run Static Analysis
        run: vendor/bin/phpstan analyse
