name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, intl, xml, sqlite3

      # Step 3: Install Composer (skip if dependencies are already installed)
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      # Step 4: Install dependencies (optional, skip if not needed)
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader

      # Step 5: Set up SQLite (if needed)
      - name: Set up SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Step 6: Run migrations (skip if database is already set up)
      - name: Run migrations
        run: php artisan migrate --no-interaction --force

      # Step 7: Run tests
      - name: Run tests
        run: php artisan test
